server:
  port: 8000

keycloak:
  realm: my_realm
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: my_client
  credentials:
    secret: ccf4955c-b206-4b78-80b1-139aac3393c4
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    root: INFO
    com.psc.sample.keycloak: DEBUG